-- MySQL Script generated by MySQL Workbench
-- qua 12 jun 2019 17:41:48 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bibliotecaLPAW
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotecaLPAW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotecaLPAW` ;
USE `bibliotecaLPAW` ;

-- -----------------------------------------------------
-- Table `bibliotecaLPAW`.`tb_editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaLPAW`.`tb_editora` (
  `idtb_editora` INT NOT NULL AUTO_INCREMENT,
  `nomeEditora` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtb_editora`),
  UNIQUE INDEX `nomeEditora_UNIQUE` (`nomeEditora` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaLPAW`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaLPAW`.`tb_categoria` (
  `idtb_categoria` INT NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtb_categoria`),
  UNIQUE INDEX `nomeCategoria_UNIQUE` (`nomeCategoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaLPAW`.`tb_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaLPAW`.`tb_livro` (
  `idtb_livro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `isbn` VARCHAR(255) NOT NULL,
  `edicao` VARCHAR(4) NULL,
  `ano` YEAR NOT NULL,
  `upload` VARCHAR(45) NULL,
  `tb_editora_idtb_editora` INT NOT NULL,
  `tb_categoria_idtb_categoria` INT NOT NULL,
  PRIMARY KEY (`idtb_livro`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC),
  INDEX `fk_tb_livro_tb_editora1_idx` (`tb_editora_idtb_editora` ASC),
  INDEX `fk_tb_livro_tb_categoria1_idx` (`tb_categoria_idtb_categoria` ASC),
  CONSTRAINT `fk_tb_livro_tb_editora1`
    FOREIGN KEY (`tb_editora_idtb_editora`)
    REFERENCES `bibliotecaLPAW`.`tb_editora` (`idtb_editora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_livro_tb_categoria1`
    FOREIGN KEY (`tb_categoria_idtb_categoria`)
    REFERENCES `bibliotecaLPAW`.`tb_categoria` (`idtb_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaLPAW`.`tb_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaLPAW`.`tb_autor` (
  `idtb_autor` INT NOT NULL AUTO_INCREMENT,
  `nomeAutor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtb_autor`),
  UNIQUE INDEX `nomeAutor_UNIQUE` (`nomeAutor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaLPAW`.`tb_autoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaLPAW`.`tb_autoria` (
  `tb_livro_idtb_livro` INT NOT NULL,
  `tb_autores_idtb_autores` INT NOT NULL,
  PRIMARY KEY (`tb_livro_idtb_livro`, `tb_autores_idtb_autores`),
  INDEX `fk_tb_livro_has_tb_autores_tb_autores1_idx` (`tb_autores_idtb_autores` ASC),
  INDEX `fk_tb_livro_has_tb_autores_tb_livro_idx` (`tb_livro_idtb_livro` ASC),
  CONSTRAINT `fk_tb_livro_has_tb_autores_tb_livro`
    FOREIGN KEY (`tb_livro_idtb_livro`)
    REFERENCES `bibliotecaLPAW`.`tb_livro` (`idtb_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_livro_has_tb_autores_tb_autores1`
    FOREIGN KEY (`tb_autores_idtb_autores`)
    REFERENCES `bibliotecaLPAW`.`tb_autor` (`idtb_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaLPAW`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaLPAW`.`tb_usuario` (
  `idtb_usuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(255) NOT NULL,
  `tipo` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `recuperar` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idtb_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaLPAW`.`tb_exemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaLPAW`.`tb_exemplar` (
  `idtb_exemplar` INT NOT NULL AUTO_INCREMENT,
  `tipoExemplar` INT NOT NULL,
  `tb_livro_idtb_livro` INT NOT NULL,
  PRIMARY KEY (`idtb_exemplar`),
  INDEX `fk_tb_exemplar_tb_livro1_idx` (`tb_livro_idtb_livro` ASC),
  CONSTRAINT `fk_tb_exemplar_tb_livro1`
    FOREIGN KEY (`tb_livro_idtb_livro`)
    REFERENCES `bibliotecaLPAW`.`tb_livro` (`idtb_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaLPAW`.`tb_emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaLPAW`.`tb_emprestimo` (
  `idtb_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `tb_usuario_idtb_usuario` INT NOT NULL,
  `tb_exemplar_idtb_exemplar` INT NOT NULL,
  `dataEmprestimo` DATE NOT NULL,
  `observacoes` TEXT(255) NULL,
  `dataVencimento` DATE NOT NULL,
  `dataDevolucao` DATE NULL,
  `situacao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idtb_emprestimo`),
  INDEX `fk_tb_usuario_has_tb_exemplar_tb_usuario1_idx` (`tb_usuario_idtb_usuario` ASC),
  INDEX `fk_tb_usuario_has_tb_exemplar_tb_exemplar1_idx` (`tb_exemplar_idtb_exemplar` ASC),
  CONSTRAINT `fk_tb_usuario_has_tb_exemplar_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idtb_usuario`)
    REFERENCES `bibliotecaLPAW`.`tb_usuario` (`idtb_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_has_tb_exemplar_tb_exemplar1`
    FOREIGN KEY (`tb_exemplar_idtb_exemplar`)
    REFERENCES `bibliotecaLPAW`.`tb_exemplar` (`idtb_exemplar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecaLPAW`.`tb_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecaLPAW`.`tb_reserva` (
  `idtb_reserva` INT NOT NULL AUTO_INCREMENT,
  `tb_usuario_idtb_usuario` INT NOT NULL,
  `tb_exemplar_idtb_exemplar` INT NOT NULL,
  `dataReserva` DATE NOT NULL,
  `observacoes` TEXT(255) NULL,
  `situacao` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idtb_reserva`),
  INDEX `fk_tb_reserva_tb_usuario1_idx` (`tb_usuario_idtb_usuario` ASC),
  INDEX `fk_tb_reserva_tb_exemplar1_idx` (`tb_exemplar_idtb_exemplar` ASC),
  CONSTRAINT `fk_tb_reserva_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idtb_usuario`)
    REFERENCES `bibliotecaLPAW`.`tb_usuario` (`idtb_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_reserva_tb_exemplar1`
    FOREIGN KEY (`tb_exemplar_idtb_exemplar`)
    REFERENCES `bibliotecaLPAW`.`tb_exemplar` (`idtb_exemplar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
